version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/webapp.war webapp.war
artifacts:
  files:
    - webapp.war
    - .ebextensions/**/*